[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/production/supervisor/supervisord.pid

[program:php-fpm]
command=/usr/sbin/php-fpm85 --nodaemonize --fpm-config /etc/php85/php-fpm.conf
autostart=true
autorestart=true
priority=10
stopsignal=QUIT
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -e /dev/stderr -g "daemon off;"
autostart=true
autorestart=true
priority=20
stopsignal=QUIT
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[include]
files=/run/production/supervisor/conf.d/*.conf
