; Desativar a exibição de erros
display_errors = Off

; Desativar o relatório de erros estritos
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

; Aumentar os limites de tempo de execução e memória
max_execution_time = 300
memory_limit = MEMORY_LIMIT

; Upload de arquivos
upload_max_filesize = UPLOAD_MAX
post_max_size = UPLOAD_MAX

; Habilitar o opcache
opcache.enable=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=60
opcache.fast_shutdown=1