; Production defaults

; Errors
display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL

; Security
expose_php = Off
cgi.fix_pathinfo = 0

; Runtime
max_execution_time = 300
max_input_time = 60

; OPcache
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
